robot2:
  planner_server:
    ros__parameters:
      expected_planner_frequency: 1.0
      use_sim_time: True
      global_frame: "map"
      planner_plugins: ["GridBased"]
      GridBased:
        plugin: "nav2_navfn_planner/NavfnPlanner"
        tolerance: 0.5
        use_astar: false
        allow_unknown: True

robot2:
  planner_server_rclcpp_node:
    ros__parameters:
      use_sim_time: True

robot2:
  global_costmap:
    global_costmap:
      ros__parameters:
        update_frequency: 1.0
        publish_frequency: 1.0
        map_topic: map
        global_frame: map
        robot_base_frame: robot2/base_footprint
        use_sim_time: True
        # height: 10
        # width: 18
        robot_radius: 0.75
        resolution: 0.05
        track_unknown_space: True
        plugins: ["static_layer", "inflation_layer"]
        obstacle_layer:
          plugin: "nav2_costmap_2d::ObstacleLayer"
          enabled: True
          observation_sources: scan
          scan:
            topic: /robot2/scan
            max_obstacle_height: 4.0
            clearing: True
            marking: True
            data_type: "LaserScan"
        static_layer:
          plugin: "nav2_costmap_2d::StaticLayer"
          subscribe_to_updates: True
          map_topic: "/map"
          map_subscribe_transient_local: True
        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          cost_scaling_factor: 3.0
          inflation_radius: 0.55
        always_send_full_costmap: True
    global_costmap_client:
      ros__parameters:
        use_sim_time: True
    global_costmap_rclcpp_node:
      ros__parameters:
        use_sim_time: True


# ---

robot1:
  planner_server:
    ros__parameters:
      expected_planner_frequency: 1.0
      use_sim_time: True
      global_frame: "map"
      planner_plugins: ["GridBased"]
      GridBased:
        plugin: "nav2_navfn_planner/NavfnPlanner"
        tolerance: 0.5
        use_astar: false
        allow_unknown: True

robot1:
  planner_server_rclcpp_node:
    ros__parameters:
      use_sim_time: True

robot1:
  global_costmap:
    global_costmap:
      ros__parameters:
        update_frequency: 1.0
        publish_frequency: 1.0
        map_topic: map
        global_frame: map
        robot_base_frame: robot1/base_footprint
        use_sim_time: True
        # height: 10
        # width: 18
        robot_radius: 0.75
        resolution: 0.05
        track_unknown_space: True
        plugins: ["static_layer", "inflation_layer"]
        obstacle_layer:
          plugin: "nav2_costmap_2d::ObstacleLayer"
          enabled: True
          observation_sources: scan
          scan:
            topic: /robot1/scan
            max_obstacle_height: 4.0
            clearing: True
            marking: True
            data_type: "LaserScan"
        static_layer:
          plugin: "nav2_costmap_2d::StaticLayer"
          subscribe_to_updates: True
          map_topic: "/map"
          map_subscribe_transient_local: True
        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          cost_scaling_factor: 3.0
          inflation_radius: 0.55
        always_send_full_costmap: True
    global_costmap_client:
      ros__parameters:
        use_sim_time: True
    global_costmap_rclcpp_node:
      ros__parameters:
        use_sim_time: True



# ---

robot3:
  planner_server:
    ros__parameters:
      expected_planner_frequency: 1.0
      use_sim_time: True
      global_frame: "map"
      planner_plugins: ["GridBased"]
      GridBased:
        plugin: "nav2_navfn_planner/NavfnPlanner"
        tolerance: 0.5
        use_astar: false
        allow_unknown: True

robot3:
  planner_server_rclcpp_node:
    ros__parameters:
      use_sim_time: True

robot3:
  global_costmap:
    global_costmap:
      ros__parameters:
        update_frequency: 1.0
        publish_frequency: 1.0
        map_topic: map
        global_frame: map
        robot_base_frame: robot3/base_footprint
        use_sim_time: True
        height: 200
        width: 200
        robot_radius: 0.75
        resolution: 0.05
        track_unknown_space: True
        plugins: ["static_layer", "inflation_layer"]
        obstacle_layer:
          plugin: "nav2_costmap_2d::ObstacleLayer"
          enabled: True
          observation_sources: scan
          scan:
            topic: /robot3/scan
            max_obstacle_height: 4.0
            clearing: True
            marking: True
            data_type: "LaserScan"
        static_layer:
          plugin: "nav2_costmap_2d::StaticLayer"
          subscribe_to_updates: True
          map_topic: "/map"
          map_subscribe_transient_local: True
        inflation_layer:
          plugin: "nav2_costmap_2d::InflationLayer"
          cost_scaling_factor: 3.0
          inflation_radius: 0.55
        always_send_full_costmap: True
    global_costmap_client:
      ros__parameters:
        use_sim_time: True
    global_costmap_rclcpp_node:
      ros__parameters:
        use_sim_time: True
